
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 30;
  public static final int POWER = 43;
  public static final int EQUALS = 34;
  public static final int UMINUS = 45;
  public static final int CASE = 40;
  public static final int GREATER = 37;
  public static final int LPAREN = 22;
  public static final int INT = 5;
  public static final int LESS = 36;
  public static final int MINUS = 28;
  public static final int STATIC = 4;
  public static final int RPAREN = 23;
  public static final int NOT = 31;
  public static final int SEMICOLON = 26;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 24;
  public static final int CLASS = 3;
  public static final int PLUS = 27;
  public static final int LESSEQ = 38;
  public static final int ASSIGN = 25;
  public static final int IF = 11;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 16;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int LCURLY = 20;
  public static final int VOID = 8;
  public static final int SWITCH = 42;
  public static final int RCURLY = 21;
  public static final int INTLITERAL = 18;
  public static final int TIMES = 29;
  public static final int COLON = 44;
  public static final int ELSE = 12;
  public static final int NOTEQUALS = 35;
  public static final int WHILE = 13;
  public static final int DEFAULT = 41;
  public static final int PUBLIC = 2;
  public static final int GREATEREQ = 39;
  public static final int STRING = 7;
  public static final int STRINGLITERAL = 19;
  public static final int FALSE = 10;
  public static final int PRINT = 15;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "STATIC",
  "INT",
  "BOOLEAN",
  "STRING",
  "VOID",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "RETURN",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "ASSIGN",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUALS",
  "NOTEQUALS",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "CASE",
  "DEFAULT",
  "SWITCH",
  "POWER",
  "COLON",
  "UMINUS"
  };
}

